 manifest:
  remotes:
    - name: mrninhvn
      url-base: https://github.com/mrninhvn
  projects:
    - name: zmk
      remote: mrninhvn
      revision: mikoto
      import: app/west.yml
  self:
    path: config