 manifest:
  remotes:
    - name: SAIXX
      url-base: https://github.com/SAIXX
  projects:
    - name: zmk
      remote: SAIXX
      revision: mikoto
      import: app/west.yml
  self:
    path: config
